title: "Nom de l'entreprise"
description: "Entreprise artisanale - Portfolio"
url: "https://ton-pseudo.github.io"
baseurl: "/testportfolio"

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

markdown: kramdown

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://www.facebook.com/tonentreprise"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/tonentreprise"

atom_feed:
  hide: true

copyright: Nom de l'entreprise. Un service BATILIBSERVICE.

minimal_mistakes_skin: "default"

sass:
  style: compressed

include:
  - assets/css

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      custom_css: "/assets/css/custom.css"
